export const productos = [
    {
      id: 1,
      titulo: "iPhone 12",
      imagen: "iphone12.jpg",
      descripcion: "El iPhone 12 es el último modelo de smartphone de Apple, con una pantalla Super Retina XDR, chip A14 Bionic y compatibilidad con la red 5G.",
      precio: 999.99,
      stock: 20,
      categoria: "Electrónica",
      destacado: true,
    },
    {
      id: 2,
      titulo: "Samsung Galaxy S21",
      imagen: "galaxyS21.jpg",
      descripcion: "El Samsung Galaxy S21 es un teléfono Android de alta gama con una pantalla Dynamic AMOLED, procesador Exynos 2100 y una cámara versátil.",
      precio: 899.99,
      stock: 15,
      categoria: "Electrónica",
      destacado: false,
    },
    {
      id: 3,
      titulo: "MacBook Pro 2021",
      imagen: "macbookPro2021.jpg",
      descripcion: "La MacBook Pro 2021 es una potente computadora portátil con el chip M1 Pro, pantalla Retina XDR y una duración de batería impresionante.",
      precio: 1999.99,
      stock: 10,
      categoria: "Electrónica",
      destacado: true,
    },
    {
      id: 4,
      titulo: "Sony 65\" OLED TV",
      imagen: "sonyOLEDtv.jpg",
      descripcion: "Disfruta de una calidad de imagen excepcional con este televisor OLED de 65 pulgadas de Sony con resolución 4K y tecnología Acoustic Surface Audio.",
      precio: 2499.99,
      stock: 8,
      categoria: "Electrónica",
      destacado: true,
    },
    {
      id: 5,
      titulo: "Nike Air Zoom Pegasus 38",
      imagen: "nikePegasus38.jpg",
      descripcion: "Las zapatillas Nike Air Zoom Pegasus 38 son ideales para correr, con una amortiguación suave y una parte superior transpirable.",
      precio: 129.99,
      stock: 25,
      categoria: "Deportes",
      destacado: false,
    },
    {
      id: 6,
      titulo: "Canon EOS R5",
      imagen: "canonEOSR5.jpg",
      descripcion: "La Canon EOS R5 es una cámara mirrorless de alta gama con sensor de fotograma completo de 45 megapíxeles y capacidad para grabación de video 8K.",
      precio: 3499.99,
      stock: 12,
      categoria: "Fotografía",
      destacado: true,
    },
    {
      id: 7,
      titulo: "KitchenAid Artisan Stand Mixer",
      imagen: "kitchenAidMixer.jpg",
      descripcion: "La batidora KitchenAid Artisan es perfecta para amasar, mezclar y batir ingredientes con facilidad. Disponible en varios colores elegantes.",
      precio: 349.99,
      stock: 18,
      categoria: "Hogar",
      destacado: false,
    },
    {
      id: 8,
      titulo: "Dyson V11 Absolute Vacuum",
      imagen: "dysonV11.jpg",
      descripcion: "El Dyson V11 Absolute es una aspiradora sin cable con potente succión, tecnología de detección de carga y accesorios versátiles para una limpieza completa.",
      precio: 599.99,
      stock: 15,
      categoria: "Hogar",
      destacado: true,
    },
    {
      id: 9,
      titulo: "Fitbit Charge 5",
      imagen: "fitbitCharge5.jpg",
      descripcion: "El Fitbit Charge 5 es una pulsera de actividad avanzada con monitorización de la salud, GPS incorporado y funciones inteligentes para un estilo de vida activo.",
      precio: 179.99,
      stock: 20,
      categoria: "Tecnología Portátil",
      destacado: true,
    },
    {
      id: 10,
      titulo: "Instant Pot Duo Evo Plus",
      imagen: "instantPot.jpg",
      descripcion: "La Instant Pot Duo Evo Plus es una olla a presión multifuncional que cocina alimentos hasta un 70% más rápido. Perfecta para cocina a presión, vapor, salteado y más.",
      precio: 129.99,
      stock: 10,
      categoria: "Cocina",
      destacado: false,
    },{
      id: 11,
      titulo: "iPhone 6",
      imagen: "iphone6.jpg",
      descripcion: "El iPhone 6 es un smartphone icónico con una pantalla Retina HD de 4.7 pulgadas, chip A8 y una cámara mejorada.",
      precio: 299.99,
      stock: 15,
      categoria: "Electrónica",
      destacado: false,
    },
    {
      id: 12,
      titulo: "Samsung Galaxy Note 20",
      imagen: "galaxyNote20.jpg",
      descripcion: "El Samsung Galaxy Note 20 es un teléfono Android con S Pen, pantalla Super AMOLED, y potentes capacidades de productividad.",
      precio: 1099.99,
      stock: 12,
      categoria: "Electrónica",
      destacado: true,
    },
    {
      id: 13,
      titulo: "MacBook Air M2",
      imagen: "macbookAirM2.jpg",
      descripcion: "La MacBook Air M2 es una computadora portátil ultraligera con el chip M2, pantalla Retina y una batería de larga duración.",
      precio: 1499.99,
      stock: 8,
      categoria: "Electrónica",
      destacado: false,
    },
    {
      id: 14,
      titulo: "Sony 55\" 4K OLED TV",
      imagen: "sony4kOLEDtv.jpg",
      descripcion: "Este televisor Sony 4K OLED de 55 pulgadas ofrece una experiencia visual impresionante con negros profundos y colores vibrantes.",
      precio: 1899.99,
      stock: 10,
      categoria: "Electrónica",
      destacado: false,
    },
    {
      id: 15,
      titulo: "Nike Air Zoom Pegasus 36",
      imagen: "nikePegasus36.jpg",
      descripcion: "Las zapatillas Nike Air Zoom Pegasus 36 son conocidas por su comodidad y rendimiento, ideales para corredores de todos los niveles.",
      precio: 109.99,
      stock: 20,
      categoria: "Deportes",
      destacado: true,
    },
    {
      id: 16,
      titulo: "Canon EOS R6",
      imagen: "canonEOSR6.jpg",
      descripcion: "La Canon EOS R6 es una cámara mirrorless versátil con enfoque automático rápido, grabación de video 4K y estabilización de imagen integrada.",
      precio: 2799.99,
      stock: 12,
      categoria: "Fotografía",
      destacado: false,
    },
    {
      id: 17,
      titulo: "KitchenAid Professional 600",
      imagen: "kitchenAidProfessional600.jpg",
      descripcion: "La batidora KitchenAid Professional 600 es una opción robusta con capacidad para grandes cantidades, perfecta para cocinar y hornear a gran escala.",
      precio: 449.99,
      stock: 15,
      categoria: "Hogar",
      destacado: true,
    },
    {
      id: 18,
      titulo: "Dyson V15 Detect Vacuum",
      imagen: "dysonV15.jpg",
      descripcion: "El Dyson V15 Detect es una aspiradora sin cable con capacidad para detectar y visualizar partículas microscópicas, proporcionando una limpieza avanzada.",
      precio: 699.99,
      stock: 18,
      categoria: "Hogar",
      destacado: false,
    },
    {
      id: 19,
      titulo: "Fitbit Sense",
      imagen: "fitbitSense.jpg",
      descripcion: "El Fitbit Sense es un reloj inteligente con avanzadas funciones de salud, incluyendo EDA Scan, medición de la temperatura de la piel y seguimiento del estrés.",
      precio: 229.99,
      stock: 22,
      categoria: "Tecnología Portátil",
      destacado: true,
    },
    {
      id: 20,
      titulo: "Instant Pot Duo Crisp",
      imagen: "instantPotDuoCrisp.jpg",
      descripcion: "La Instant Pot Duo Crisp combina funciones de olla a presión y freidora de aire, permitiéndote cocinar una variedad de platos deliciosos de manera rápida y saludable.",
      precio: 179.99,
      stock: 10,
      categoria: "Cocina",
      destacado: true,
    },
  ];
  